### ISSUE TITLE
Today Design

### ISSUE THREAD

**Issue by adk96r** [Adk0096/Today#2]
![cardlayout1](https://cloud.githubusercontent.com/assets/19271795/21353083/71f9828c-c6ea-11e6-9052-0f127baf5aa1.jpg)
![days1](https://cloud.githubusercontent.com/assets/19271795/21353087/735a58cc-c6ea-11e6-9c73-392c78688fa3.jpg)

**Comment by Adk0096** [comment]
![insidecard](https://cloud.githubusercontent.com/assets/19271795/21356197/be95e53e-c6f6-11e6-92a7-3a13c691e7e3.png)

**Comment by adk96r** [comment]
![insidecard](https://cloud.githubusercontent.com/assets/19271795/21357230/771028d8-c6fa-11e6-95b5-a22104b04f92.png)
